interface ZIF_PT_I_PROJECT_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZPT_I_PROJECT,
 CREATE_ZPT_I_PROJECT           TYPE /BOBF/ACT_KEY VALUE 'FA163EA6641C1EDB808E17EA575487DA',
 DELETE_ZPT_I_PROJECT           TYPE /BOBF/ACT_KEY VALUE 'FA163EA6641C1EDB808E17EA575507DA',
 LOCK_ZPT_I_PROJECT             TYPE /BOBF/ACT_KEY VALUE 'FA163EA6641C1EDB808E17EA5753C7DA',
 SAVE_ZPT_I_PROJECT             TYPE /BOBF/ACT_KEY VALUE 'FA163EA6641C1EDB808E17EA575587DA',
 UNLOCK_ZPT_I_PROJECT           TYPE /BOBF/ACT_KEY VALUE 'FA163EA6641C1EDB808E17EA575407DA',
 UPDATE_ZPT_I_PROJECT           TYPE /BOBF/ACT_KEY VALUE 'FA163EA6641C1EDB808E17EA5754C7DA',
 VALIDATE_ZPT_I_PROJECT         TYPE /BOBF/ACT_KEY VALUE 'FA163EA6641C1EDB808E17EA575547DA',
      END OF ZPT_I_PROJECT,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZPT_I_PROJECT,
        BEGIN OF LOCK_ZPT_I_PROJECT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZPT_I_PROJECT,
        BEGIN OF UNLOCK_ZPT_I_PROJECT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZPT_I_PROJECT,
      END OF ZPT_I_PROJECT,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZPT_I_PROJECT,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE 'FA163EA6641C1EDB808E17EA575667DA',
      END OF ZPT_I_PROJECT,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZPT_I_PROJECT,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE 'FA163EA6641C1EDB808E17EA5753A7DA',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE 'FA163EA6641C1EDB808E17EA575367DA',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE 'FA163EA6641C1EDB808E17EA575467DA',
      END OF ZPT_I_PROJECT,
      BEGIN OF ZPT_I_PROJECT_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'FA163EA6641C1EDB808E17EA5755E7DA',
      END OF ZPT_I_PROJECT_LOCK,
      BEGIN OF ZPT_I_PROJECT_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'FA163EA6641C1EDB808E17EA5755C7DA',
      END OF ZPT_I_PROJECT_MESSAGE,
      BEGIN OF ZPT_I_PROJECT_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'FA163EA6641C1EDB808E17EA575607DA',
      END OF ZPT_I_PROJECT_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZPT_I_PROJECT,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZPT_I_PROJECT,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE 'FA163EA6641C1EDB808E17EA5752C7DA' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZPT_I_PROJECT' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZPT_I_PROJECT,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE 'FA163EA6641C1EDB808E17EA575687DA',
 ADMIN_DATA                     TYPE /BOBF/DET_KEY VALUE 'FA163EA6641C1EDB80BF8FB19BC2E446',
      END OF ZPT_I_PROJECT,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZPT_I_PROJECT                  TYPE /BOBF/OBM_NODE_KEY VALUE 'FA163EA6641C1EDB808E17EA575307DA',
 ZPT_I_PROJECT_LOCK             TYPE /BOBF/OBM_NODE_KEY VALUE 'FA163EA6641C1EDB808E17EA575387DA',
 ZPT_I_PROJECT_MESSAGE          TYPE /BOBF/OBM_NODE_KEY VALUE 'FA163EA6641C1EDB808E17EA575347DA',
 ZPT_I_PROJECT_PROPERTY         TYPE /BOBF/OBM_NODE_KEY VALUE 'FA163EA6641C1EDB808E17EA575447DA',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZPT_I_PROJECT,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  PROJECT_NO                     TYPE STRING VALUE 'PROJECT_NO',
  NAME                           TYPE STRING VALUE 'NAME',
  STARTED_ON                     TYPE STRING VALUE 'STARTED_ON',
  ENDED_ON                       TYPE STRING VALUE 'ENDED_ON',
  TR_TARGET                      TYPE STRING VALUE 'TR_TARGET',
  CTS_PROJECT                    TYPE STRING VALUE 'CTS_PROJECT',
  ADMIN_DATA                     TYPE STRING VALUE 'ADMIN_DATA',
  CREA_DATE_TIME                 TYPE STRING VALUE 'CREA_DATE_TIME',
  CREA_UNAME                     TYPE STRING VALUE 'CREA_UNAME',
  LCHG_DATE_TIME                 TYPE STRING VALUE 'LCHG_DATE_TIME',
  LCHG_UNAME                     TYPE STRING VALUE 'LCHG_UNAME',
      END OF ZPT_I_PROJECT,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZPT_I_PROJECT,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE 'FA163EA6641C1EDB808E17EA575327DA',
      END OF ZPT_I_PROJECT,
    END OF SC_NODE_CATEGORY .
endinterface.
